### ISSUE TITLE
Add alternative Quad9 IP's

### ISSUE THREAD

**Issue by SUNWfrk** [oikuda/stubby-quad9#1]
Hello,

Like this docker, so thanks for it! Maybe it might be a good idea to add the alternative QUAD9 dns servers:

dns.quad9.net has address 149.112.112.112
dns.quad9.net has address 9.9.9.9
dns.quad9.net has IPv6 address 2620:fe::fe

Thanks,
Bart

**Comment by oikuda** [comment]
Hello,

Glad you like it!
Thanks for the info, wasn't aware of these additional addresses.
I added the alternative IPv4 address to the master branch in a679e5a.
I'm still running it on a IPv4 only network, so after some testing i decided to exclude the IPv6 address from the master branch.

I created two new branches:
- [v46](https://github.com/oikuda/stubby-quad9/tree/v46) - IPv4 and IPv6 addresses
- [v6](https://github.com/oikuda/stubby-quad9/tree/v6) - only IPv6 addresses

Each of them has a build on dockerhub:
```bash
docker pull oikuda/stubby-quad9:v46
docker pull oikuda/stubby-quad9:v6
```
Cheers,
Valter
